# Generated by Django 2.2.3 on 2019-07-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'db_table': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=50, verbose_name='fuel')),
                ('unit', models.CharField(max_length=5, verbose_name='unit')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building', verbose_name='building')),
            ],
            options={
                'verbose_name': 'ModelName',
                'verbose_name_plural': 'ModelNames',
                'db_table': 'meters',
            },
        ),
    ]
