# Generated by Django 2.2.3 on 2019-07-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meter',
            options={'verbose_name': 'meter', 'verbose_name_plural': 'meters'},
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.FloatField(verbose_name='consumption')),
                ('reading_date_time', models.DateTimeField(verbose_name='reading date')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Meter', verbose_name='meter')),
            ],
            options={
                'verbose_name': 'energy',
                'verbose_name_plural': 'energy',
                'db_table': 'energy',
            },
        ),
    ]
