# Generated by Django 2.2.3 on 2019-07-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20190709_0914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='energy',
            unique_together={('meter', 'reading_date_time')},
        ),
    ]
